/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import entidades.Cliente;
import entidades.Productos;
import java.awt.Component;
import javax.swing.*;

/**
 *
 * @author isran
 */
public class Producto extends javax.swing.JFrame {
    protected Productos producto;
    Cliente cliente;
    /**
     * Creates new form Producto
     */
    public Producto(Productos producto) {
        this.producto = producto;
        initComponents();
        expositor.setLayout(new BoxLayout(expositor, BoxLayout.Y_AXIS));
        generarProducto();
    }
    
    private void generarProducto() {
        expositor.removeAll();
        
        //JLabel con el nombre del producto y su personalizacion
        JLabel nombre = new JLabel(producto.getNombre());
        nombre.setAlignmentX(Component.RIGHT_ALIGNMENT);
        nombre.setAlignmentY(Component.CENTER_ALIGNMENT);
        nombre.setFont(nombre.getFont().deriveFont(40f)); 
        expositor.add(nombre);
        
        //JLabel con el categoria del producto y su personalizacion
        JLabel categoria = new JLabel(producto.getCategoria().toString());
        categoria.setAlignmentX(Component.RIGHT_ALIGNMENT);
        categoria.setAlignmentY(Component.CENTER_ALIGNMENT);
        nombre.setFont(nombre.getFont().deriveFont(20f));
        expositor.add(categoria);
        
        //JLabel con el precio del producto y su personalizacion
        JLabel precio = new JLabel(String.valueOf(producto.getPrecio())+ "€");
        precio.setAlignmentX(Component.RIGHT_ALIGNMENT);
        precio.setAlignmentY(Component.CENTER_ALIGNMENT);
        nombre.setFont(nombre.getFont().deriveFont(35f));
        expositor.add(precio);
        
        JLabel valoracion = new JLabel(String.valueOf(producto.getPrecio())+ "€");
        precio.setAlignmentX(Component.RIGHT_ALIGNMENT);
        precio.setAlignmentY(Component.CENTER_ALIGNMENT);
        nombre.setFont(nombre.getFont().deriveFont(35f));
        expositor.add(precio);
        
        
        
        expositor.revalidate();
        expositor.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        volver = new javax.swing.JButton();
        botonCarrito = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        expositor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        volver.setBackground(new java.awt.Color(153, 204, 255));
        volver.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        volver.setText("<-- Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        botonCarrito.setBackground(new java.awt.Color(153, 204, 255));
        botonCarrito.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botonCarrito.setText("Carrito");
        botonCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCarritoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout expositorLayout = new javax.swing.GroupLayout(expositor);
        expositor.setLayout(expositorLayout);
        expositorLayout.setHorizontalGroup(
            expositorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 833, Short.MAX_VALUE)
        );
        expositorLayout.setVerticalGroup(
            expositorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(expositor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(volver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonCarrito)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 835, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volver, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        Main ventanaMain = new Main(cliente, null);
           this.setVisible(false);
           ventanaMain.setVisible(true);
    }//GEN-LAST:event_volverActionPerformed

    private void botonCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCarritoActionPerformed
        Carrito jCarrito = new Carrito(cliente, null);
        this.setVisible(false);
        jCarrito.setVisible(true);
    }//GEN-LAST:event_botonCarritoActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCarrito;
    private javax.swing.JPanel expositor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
